In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['creditcard.csv']


In [2]:
df = pd.read_csv('../input/creditcard.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
Time      284807 non-null float64
V1        284807 non-null float64
V2        284807 non-null float64
V3        284807 non-null float64
V4        284807 non-null float64
V5        284807 non-null float64
V6        284807 non-null float64
V7        284807 non-null float64
V8        284807 non-null float64
V9        284807 non-null float64
V10       284807 non-null float64
V11       284807 non-null float64
V12       284807 non-null float64
V13       284807 non-null float64
V14       284807 non-null float64
V15       284807 non-null float64
V16       284807 non-null float64
V17       284807 non-null float64
V18       284807 non-null float64
V19       284807 non-null float64
V20       284807 non-null float64
V21       284807 non-null float64
V22       284807 non-null float64
V23       284807 non-null float64
V24       284807 non-null float64
V25       284807 non-null float64
V26  

In [4]:
df.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

### Downsampling

In [5]:
df = df.sample(frac=1, random_state = 42)
fraud_df = df.loc[df['Class'] == 1]
non_fraud_df = df.loc[df['Class'] == 0][:492]

normal_distributed_df = pd.concat([fraud_df, non_fraud_df])

new_df = normal_distributed_df.sample(frac=1, random_state=42)
new_df.head(5)

Time        V1        V2        V3        V4        V5        V6  \
146884   87941.0  2.054361 -0.122642 -1.245717  0.189567  0.132497 -0.620765   
95597    65385.0 -2.923827  1.524837 -3.018758  3.289291 -5.755542  2.218276   
96768    65927.0  0.955253 -0.833374  0.847147  0.725970 -1.322868 -0.238842   
75511    56098.0 -1.229669  1.956099 -0.851198  2.796987 -1.913977 -0.044934   
255556  157284.0 -0.242245  4.147186 -5.672349  6.493741  1.591168 -1.602523   

              V7        V8        V9  ...       V21       V22       V23  \
146884  0.059581 -0.148058  0.338940  ... -0.271204 -0.687048  0.271569   
95597  -0.509995 -3.569444 -1.016592  ... -0.511657 -0.122724 -4.288639   
96768  -0.565347  0.022443 -0.762247  ... -0.110554 -0.129397 -0.040892   
75511  -1.340739 -0.555548 -1.184468  ...  1.208054  0.277612  0.019266   
255556 -0.950463  0.722903 -4.128505  ...  0.249023 -0.480286 -0.286080   

             V24       V25       V26       V27       V28   Amount  Class  
146884 -0.497120 -0.270115  0.208619 -0.076075 -0.075428     0.99      0  
95597   0.563797 -0.949451 -0.204532  1.510206 -0.324706  1354.25      1  
96768   0.364872  0.204756 -0.304578  0.055908  0.062489   156.00      0  
75511   0.508529 -0.201183 -0.249600  0.562239  0.075309   170.92      1  
255556 -1.153575 -0.035571  0.559628  0.409446  0.221048     0.77      1  

[5 rows x 31 columns]

In [6]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 984 entries, 146884 to 149869
Data columns (total 31 columns):
Time      984 non-null float64
V1        984 non-null float64
V2        984 non-null float64
V3        984 non-null float64
V4        984 non-null float64
V5        984 non-null float64
V6        984 non-null float64
V7        984 non-null float64
V8        984 non-null float64
V9        984 non-null float64
V10       984 non-null float64
V11       984 non-null float64
V12       984 non-null float64
V13       984 non-null float64
V14       984 non-null float64
V15       984 non-null float64
V16       984 non-null float64
V17       984 non-null float64
V18       984 non-null float64
V19       984 non-null float64
V20       984 non-null float64
V21       984 non-null float64
V22       984 non-null float64
V23       984 non-null float64
V24       984 non-null float64
V25       984 non-null float64
V26       984 non-null float64
V27       984 non-null float64
V28       984 non-n

In [7]:
X = new_df.drop('Class', axis = 1)
y = new_df['Class']

print("X.shape: ", X.shape)
print("y.shape: ", y.shape)

X.shape:  (984, 30)
y.shape:  (984,)


In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, stratify = y, random_state = 42)

print("X_train.shape: ", X_train.shape)
print("X_test.shape: ", X_test.shape)
print("y_train.shape: ", y_train.shape)
print("y_test.shape: ", y_test.shape)

X_train.shape:  (787, 30)
X_test.shape:  (197, 30)
y_train.shape:  (787,)
y_test.shape:  (197,)


In [9]:
from sklearn.preprocessing import StandardScaler

sc_model = StandardScaler()
sc_model.fit(X_train)

X_train_std = sc_model.transform(X_train)
X_test_std = sc_model.transform(X_test)

print("X_train_std.shape: ", X_train_std.shape)
print("X_test_std.shape: ", X_test_std.shape)

X_train_std.shape:  (787, 30)
X_test_std.shape:  (197, 30)


### Logistic Regression 

In [10]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression

In [11]:
log_model = LogisticRegression(solver = 'lbfgs', random_state = 42)
log_scores = cross_val_score(log_model, X_train_std, y_train, cv = 10)
print("log_scores: ", log_scores)
print("Mean score: ", log_scores.mean())
print("Std deviation: ", log_scores.std())

log_scores:  [0.9125     0.975      0.925      0.96202532 0.93589744 0.96153846
 0.94871795 0.98717949 0.91025641 0.96153846]
Mean score:  0.9479653521583901
Std deviation:  0.024875943538302702


In [12]:
log_model.fit(X_train_std, y_train)
log_model_score = log_model.score(X_test_std, y_test)
log_model_score

0.9289340101522843

In [13]:
log_yy_pred = log_model.predict(X_test_std) 
log_model_confMatrix = confusion_matrix(y_true=y_test, y_pred=log_yy_pred)
tn, fp, fn, tp = confusion_matrix(y_true=y_test, y_pred=log_yy_pred).ravel()
print(tn, fp, fn, tp)

print(log_model_confMatrix)

96 3 11 87
[[96  3]
 [11 87]]


In [14]:
print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=log_yy_pred))
print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=log_yy_pred))
print('F1: %.3f' % f1_score(y_true=y_test, y_pred=log_yy_pred))

Precision: 0.967
Recall: 0.888
F1: 0.926


### 2.1 Support Vector Machines - SVC linear  

In [15]:
from sklearn.svm import SVC

In [16]:
svm_linear_model = SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=42,
  shrinking=True, tol=0.001, verbose=False)

In [17]:
svm_linear_scores = cross_val_score(svm_linear_model, X_train_std, y_train, cv = 10)
print("svm_linear_scores: ", svm_linear_scores)
print("Mean score: ", svm_linear_scores.mean())
print("Std deviation: ", svm_linear_scores.std())

svm_linear_scores:  [0.9125     0.975      0.9375     0.93670886 0.93589744 0.96153846
 0.94871795 0.98717949 0.8974359  0.96153846]
Mean score:  0.9454016553067186
Std deviation:  0.026009236719929392


In [18]:
svm_linear_model.fit(X_train_std, y_train)
svm_linear_score = svm_linear_model.score(X_test_std, y_test)

svm_linear_score

0.9137055837563451

In [19]:
svm_linear_yy_pred = svm_linear_model.predict(X_test_std) 
svm_linear_model_confMatrix = confusion_matrix(y_true=y_test, y_pred=svm_linear_yy_pred)
print(svm_linear_model_confMatrix)

[[97  2]
 [15 83]]


In [20]:
print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=svm_linear_yy_pred))
print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=svm_linear_yy_pred))
print('F1: %.3f' % f1_score(y_true=y_test, y_pred=svm_linear_yy_pred))

Precision: 0.976
Recall: 0.847
F1: 0.907


### 2.2 Support Vector Machines - SVC Kernal(rbf)

In [21]:
svm_rbf_model = SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.6, kernel='rbf',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False)

In [22]:
svm_rbf_scores = cross_val_score(svm_rbf_model, X_train_std, y_train, cv = 10)
print("svm_rbf_scores: ", svm_rbf_scores)
print("Mean score: ", svm_rbf_scores.mean())
print("Std deviation: ", svm_rbf_scores.std())

svm_rbf_scores:  [0.7875     0.825      0.85       0.89873418 0.80769231 0.87179487
 0.84615385 0.87179487 0.84615385 0.85897436]
Mean score:  0.8463798279779292
Std deviation:  0.031024687256243348


In [23]:
svm_rbf_model.fit(X_train_std, y_train)
svm_rbf_score = svm_rbf_model.score(X_test_std, y_test)
svm_rbf_score

0.8426395939086294

In [24]:
svm_rbf_yy_pred = svm_rbf_model.predict(X_test_std) 
svm_rbf_model_confMatrix = confusion_matrix(y_true=y_test, y_pred=svm_rbf_yy_pred)
print(svm_rbf_model_confMatrix)

[[74 25]
 [ 6 92]]


In [25]:
print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=svm_rbf_yy_pred))
print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=svm_rbf_yy_pred))
print('F1: %.3f' % f1_score(y_true=y_test, y_pred=svm_rbf_yy_pred))

Precision: 0.786
Recall: 0.939
F1: 0.856


### 3. Decision Tree Classifier

In [26]:
from sklearn.tree import DecisionTreeClassifier

In [27]:
tree_clf_model = DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=3,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [28]:
tree_clf_scores = cross_val_score(tree_clf_model, X_train_std, y_train, cv = 10)
print("tree_clf_scores: ", tree_clf_scores)
print("Mean score: ", tree_clf_scores.mean())
print("Std deviation: ", tree_clf_scores.std())

tree_clf_scores:  [0.9        0.9375     0.9125     0.93670886 0.91025641 0.93589744
 0.8974359  0.93589744 0.92307692 0.93589744]
Mean score:  0.9225170399221032
Std deviation:  0.015329906241594604


In [29]:
tree_clf_model.fit(X_train_std, y_train)
tree_clf_score = tree_clf_model.score(X_test_std, y_test)
tree_clf_score

0.9086294416243654

In [30]:
tree_clf_yy_pred = tree_clf_model.predict(X_test_std) 
tree_clf_model_confMatrix = confusion_matrix(y_true=y_test, y_pred=tree_clf_yy_pred)
print(tree_clf_model_confMatrix)

[[95  4]
 [14 84]]


In [31]:
print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=tree_clf_yy_pred))
print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=tree_clf_yy_pred))
print('F1: %.3f' % f1_score(y_true=y_test, y_pred=tree_clf_yy_pred))

Precision: 0.955
Recall: 0.857
F1: 0.903
